import re
import numpy as np
import matplotlib.pyplot as plt

enzymes = {
    "ecoRI": {"sequence": "GAATTC", "cleavage": 1},
    "bamHI": {"sequence": "GGATCC", "cleavage": 1},
    "hindIII": {"sequence": "AAGCTT", "cleavage": 1},
    "taqI": {"sequence": "TCGA", "cleavage": 1},
    "haeIII": {"sequence": "GGCC", "cleavage": 2}
}

def findCleavageSites(dnaSeq, enzyme):
    recog = enzyme["sequence"]
    offset = enzyme["cleavage"]

    matches = re.finditer(f"(?={recog})", dnaSeq)
    return [match.start() for match in matches]

def digestDna(dnaSeq, enzymes):
    fragmentInfo = {}

    for enzymeName, enzyme in enzymes.items():
        cuts = findCleavageSites(dnaSeq, enzyme)
        allCuts = [0] + cuts + [len(dnaSeq)]
        fragmentSizes = [allCuts[i+1] - allCuts[i] for i in range(len(allCuts)-1)]

        fragmentInfo[enzymeName] = {
            "cuts": cuts,
            "sizes": sorted(fragmentSizes, reverse=True)
        }

    return fragmentInfo

def plotGel(fragmentInfo):
    plt.figure(figsize=(6, 10))
    ax = plt.gca()
    ax.set_facecolor("black")

    laneSpacing = 3
    bandWidth = 0.8
    gelHeight = 500

    allSizes = [size for info in fragmentInfo.values() for size in info["sizes"]]
    maxBp = max(allSizes)
    minBp = min(allSizes)

    def migration(length):
        return 30 + (1 - (length - minBp) / (maxBp - minBp)) * gelHeight

    for laneIndex, (enzymeName, info) in enumerate(fragmentInfo.items()):
        x = 2 + laneIndex * laneSpacing

        plt.hlines(20, x - 0.6, x + 0.6, color="white", linewidth=6)

        for size in info["sizes"]:
            y = migration(size)
            plt.hlines(y, x - bandWidth/2, x + bandWidth/2, color="white", linewidth=4)

        plt.text(x, 10, enzymeName, color="white", ha="center")

    plt.xlim(0, laneSpacing * (len(fragmentInfo) + 1))
    plt.ylim(0, gelHeight + 80)
    ax.invert_yaxis()
    plt.xticks([])
    plt.yticks([])
    plt.title("Simulated Restriction Digest Gel", color="white")
    plt.show()

dnaSeq = "TCAATTATATTCAGCATGGAAAGAATAAAAGAACTACGGAATCTAATGTCGCAGTCTCGCACCCGCGAGATACTAACAAAAACCACAGTGGACCATATGGCCATAATTAAGAAGTACACATCGGGGAGACAGGAAAAGAACCCGTCACTTAGAATGAAATGGATGATGGCAATGAAATATCCAATTACTGCTGACAAAAGGATAACAGAAATGGTTCCAGAGAGAAATGAACAAGGACAAACCCTATGGAGTAAAATGAGTGATGCTGGGTCAGATAGAGTGATGGTATCACCTTTGGCTGTAACATGGTGGAATAGAAATGGGCCCGTGACAAATACGGTCCATTACCCAAAAGTGTACAAAACTTATTTTGACAAAGTCGAAAGGTTGAAACATGGAACCTTCGGCCCTGTCCATTTTAGAAACCAAGTCAAAATACGTAGAAGAGTAGACACAAACCCTGGTCATGCAGACCTCAGTGCCAAAGAGGCACAAGATGTAATTATGGAAGTTGTTTTTCCCAATGAAGTGGGGGCCAGAATACTAACATCAGAATCACAGCTAACAATAACCAAAGAGAAAAAAGAAGAACTCCGAGATTGCAAAATTTCCCCCTTGATGGTCGCATACATGCTAGAGAGAGAACTTGTGCGGAAAACAAGATTTCTCCCAGTTGCTGGCGGAACAAGCAGTATATACATTGAAGTTTTACATTTGACTCAAGGAACGTGTTGGGAACAAATGTACACTCCAGGTGGAGGAGTGAGGAATGACGATGTTGACCAAAGCCTAATTATTGCGGCCAGGAACATAGTGAGAAGAGCCGCAGTGTCAGCAGATCCACTCGCATCTTTATTGGAGATGTGCCACAGCACGCAAATTGGCGGAACAAGGATGGTGGACATTCTTAGGCAGAACCCGACTGAAGAACAAGCTGTGGATATATGCAAAGCTGCAATGGGATTGAGAATCAGCTCATCTTTCAGCTTTGGTGGCTTTACATTTAAAAGAACGAGCGGGTCGTCAGTCAAAAGAGATGAAGAGGTTCTTACAGGTAATCTCCAAACATTGAGAATAAGAGTACATGAGGGGTATGAGGAATTCACAATGGTGGGGAAAAGAGCAACAGCTATACTAAGAAAAGCAACCAGAAGACTGGTTCAACTCATAGTGAGTGGAAGAGACGAACAGTCAGTAGCCGAGGCAATAATCGTGGCCATGGTTTTTTCCCAAGAAGATTGCATGATAAAAGCAGTTAGAGGTGACCTGAATTTTGTCAACAGAGCAAATCAGCGGTTGAACCCCATGCATCAGCTTTTAAGGCATTTTCAGAAAGATGCGAAAGTACTCTTTCAAAATTGGGGAGTTGAACACATCGACAGTGTGATGGGAATGGTTGGAGTATTACCAGATATGACTCCAAGCACAGAGATGTCAATGAGAGGAATAAGAGTCAGCAAAATGGGCGTGGATGAATACTCCAGTACAGAGAGGGTGGTGGTTAGCATTGATAGGTTTTTGAGAGTTCGAGACCAACGGGGGAATGTATTGTTATCTCCTGAGGAAGTCAGTGAAACACAAGGAACTGAAAGACTGACCATAACTTATTCATCATCGATGATGTGGGAAATTAATGGGCCTGAGTCGGTTTTGGTCAATACCTATCAATGGATCATCAGGAATTGGGAAGCTATCAAAATTCAGTGGTCTCAGAACCCTGCAATGTTGTACAACAAAATGGAATTTGAACCATTTCAATCTTTAGTCCCCAAGGCCACTAGAAGCCAATACAGTGGGTTTGTCAGAACTCTATTCCAACAAATGAGAGACGTACTTGGGACATTTGACACTGCCCAGATAATAAAGCTTCTCCCTTTTGCAGCTGCTCCACCAAAGCAAAGCAGAATGCAGTTCTCTTCACTGACTGTGAATGTGAGGGGATCAGGGATGAGAATACTTGTAAGGGGCAATTCTCCTGTATTCAACTACAACAAGACCACTAAAAGGCTAACAATTCTTGGAAAAGATGCCGGCACTTTAATTGAAGACCCAGATGAAAGCACATCCGGAGTGGAGTCCGCCGTCTTGAGAGGGTTCCTCATTATAGGTAAAGAAGACAGAAGATACGGACCAGCATTAAGCATCAATGAACTGAGTAACCTTGCAAAAGGGGAAAAGGCTAATGTGTTAATTGGGCAAGGAGACGTGGTGTTGGTAATGAAACGGAAACGGGACTCTAGTATACTTACTGACAGCCAGACAGCGACCAAACGAATTCGGATGGCCATCAATTAATATTGAATAGTTTAAAAACGA"

fragmentInfo = digestDna(dnaSeq, enzymes)

for enzyme, info in fragmentInfo.items():
    print(f"\n{enzyme}:")
    print("  cuts:", info["cuts"])
    print("  fragment sizes:", info["sizes"])

plotGel(fragmentInfo)
