# 1. Take an arbitrary DNA sequence from the NCBI (National Center for Biotechnology), between 1000 and 3000 nucleotides (letters).
# 2. Implement a software application that detects repetitions (between 6b and 10b) in this DNA sequence.

from collections import Counter

# https://www.ncbi.nlm.nih.gov/nuccore/JC598668.1?report=fasta
S = """GCTAGGGGTTCGACGAAATTTTTTTTTATACAGTGTGTGGCCGCGAGAGGGTTAGAGGGTTTGGCACAAG
TTTGGCGGCAGCTCCAGCATCCGTTTTTGGAACTCGATTCCGATTACCGCAGGTCTCTCGGACTAGTTGA
GAGGGTAAGTGTTTTGTTTTTGTTTTATTAATTTGTTCTGTGTTTCCTTCTCCCTATACAAACGTGTTTG
TTAATTTATAGGCTTGTATGCCCCGCTTCATTTCACTCATTATGTAGGCGTTACACTGACCTTTGCACTG
CGTCGGGGATCTATGGGTTTCTGTGTGCTTACTACGATTTTAAACTTGTTATTTTACGGTTTGAATTTTT
AATACTTGTCCTCGTTGAATAGATGATAGCCTGTTAATAGATTTGAGTCAGGCATTGCGGAGTTATATGT
TACGCGGTTCCCAGCCTATAAGAATCGTGGTGTTGGCGCCAAAAAATGCGCGCCAACAAAAAGGCGCCAA
AAAATTGCGCGCCATTGTTTGGCGCCTTTTTCTGCGCCGTTTTCAAAATCGCGCCATACCAATTTCAAAG
TTCCCGCCATTTGGCCAACACGCTATTATCCCTGCATGATCTTCTTTAATTGGACGACATTCCTCGATTC
CCGATCCACATATCCAGTGACAGGAGTTCGGAATAAACGTTGTGATACGCGATCGAGTTCGCGCCATACC
AATTTCAAAGTTCCCGCCATTTGGCCAACACGCTATTATCCCTGCATGATCTTCTTTAATTGGACGACAT
TCCTCGATTCCCGATCCACATATCCAGTGACAGGAGTTCGGAATAAACGTTGTGATACGCGATCGAGTTT
TCGTGGCATATTCCTACGGAAACCTATTGTTCTGTGGTTGGTTTCGATCTATCGTTCTCGTACTGCGTGA
CCTCTACGGAACAATAGTTTTCCAGGAGATTTCCCGGTTTCGACTGCCGAAGCATGGAAACGTCCTGGGA
AAATCTGTTGTTCCGTAGTGTTCTCGTGACACTAACTCGAGATCCCTGCGAAATGACAGTTTTCTCTGGG
AATTACATCGTCCTGATTGTCGCGACATGGAATGGAAGCCTCATAGGAAGAACTCGATGTGATGATGCTC
TCTAGCCAAGAGAGCCGCGAACGCTCCAAGGAGAACTGTTATCTCGGGGAGATCTCGATCTCTCCTACCA
GCAACTCGAGATCTCTACGAGATTACAGTTTTTGGGGGAAATGTGTCCTCAGAACTGCTTAATCGTAGAA
GCTTCCTAGTGGATGGCGTTGTCTCGTAGAGGTCCAGATCTCTCCTGTTGGCAACTCGAAATCTCTACGA
GATAACAGTTTGTCTAGGAAACTTTCCTCCCAACTAAAGAGCGATGACTTAGGAAGTAAACGTGCCCTCA
TCACCGCCCTTACACACTGCTAGTCATTCATGTACATTGCGATTGTGCCTTGGTGCGGGGCGGTTCCTAG
GCACCATTTATCTTGTATTCCTGTACATCCCCTCCTTAATACTTTAATTGGAGCCACATCGTTTTGCCAT
GTTGATCTGTTTCCTTTCCCTGTAACAATGGTTACATTCTAAACGAACTAACTTGCTTTGAAGAAATCTA
CGAATTGATAGACTGTATATGCGCCCCTTTTCTTTATTAAAAACGCTTAACAAGGTAACAATATACGTAA
CATTCGAACAAGTACCAAGATAACTATATAACGGCTTATATAACTATC"""

def getRepeats(seq):
    seq = seq.replace("\n", "")
    repeated = {}

    for length in range(6, 11):
        subSequences = [seq[i:i+length] for i in range(len(seq) - length + 1)]
        counts = Counter(subSequences)
        repeated[length] = {sub: count for sub, count in counts.items() if count > 1}

    return repeated

repeats = getRepeats(S)

for length, subSequences in repeats.items():
    print(f"\n\nLength {length}-base repeats:\n")
    if not subSequences:
        print("  No repeats found.")
    else:
        for sub, count in subSequences.items():
            print(f"  {sub} → {count} times")
