# 1. Take an arbitrary DNA sequence from the NCBI (National Center for Biotechnology), between 1000 and 3000 nucleotides (letters).
# 2. Implement a software application that detects repetitions (between 6b and 10b) in this DNA sequence.
# 3. plot the frequencies of the repetitions found

from collections import Counter
import matplotlib.pyplot as plt

# https://www.ncbi.nlm.nih.gov/nuccore/JC598668.1?report=fasta
S = """GCTAGGGGTTCGACGAAATTTTTTTTTATACAGTGTGTGGCCGCGAGAGGGTTAGAGGGTTTGGCACAAG
TTTGGCGGCAGCTCCAGCATCCGTTTTTGGAACTCGATTCCGATTACCGCAGGTCTCTCGGACTAGTTGA
GAGGGTAAGTGTTTTGTTTTTGTTTTATTAATTTGTTCTGTGTTTCCTTCTCCCTATACAAACGTGTTTG
TTAATTTATAGGCTTGTATGCCCCGCTTCATTTCACTCATTATGTAGGCGTTACACTGACCTTTGCACTG
CGTCGGGGATCTATGGGTTTCTGTGTGCTTACTACGATTTTAAACTTGTTATTTTACGGTTTGAATTTTT
AATACTTGTCCTCGTTGAATAGATGATAGCCTGTTAATAGATTTGAGTCAGGCATTGCGGAGTTATATGT
TACGCGGTTCCCAGCCTATAAGAATCGTGGTGTTGGCGCCAAAAAATGCGCGCCAACAAAAAGGCGCCAA
AAAATTGCGCGCCATTGTTTGGCGCCTTTTTCTGCGCCGTTTTCAAAATCGCGCCATACCAATTTCAAAG
TTCCCGCCATTTGGCCAACACGCTATTATCCCTGCATGATCTTCTTTAATTGGACGACATTCCTCGATTC
CCGATCCACATATCCAGTGACAGGAGTTCGGAATAAACGTTGTGATACGCGATCGAGTTCGCGCCATACC
AATTTCAAAGTTCCCGCCATTTGGCCAACACGCTATTATCCCTGCATGATCTTCTTTAATTGGACGACAT
TCCTCGATTCCCGATCCACATATCCAGTGACAGGAGTTCGGAATAAACGTTGTGATACGCGATCGAGTTT
TCGTGGCATATTCCTACGGAAACCTATTGTTCTGTGGTTGGTTTCGATCTATCGTTCTCGTACTGCGTGA
CCTCTACGGAACAATAGTTTTCCAGGAGATTTCCCGGTTTCGACTGCCGAAGCATGGAAACGTCCTGGGA
AAATCTGTTGTTCCGTAGTGTTCTCGTGACACTAACTCGAGATCCCTGCGAAATGACAGTTTTCTCTGGG
AATTACATCGTCCTGATTGTCGCGACATGGAATGGAAGCCTCATAGGAAGAACTCGATGTGATGATGCTC
TCTAGCCAAGAGAGCCGCGAACGCTCCAAGGAGAACTGTTATCTCGGGGAGATCTCGATCTCTCCTACCA
GCAACTCGAGATCTCTACGAGATTACAGTTTTTGGGGGAAATGTGTCCTCAGAACTGCTTAATCGTAGAA
GCTTCCTAGTGGATGGCGTTGTCTCGTAGAGGTCCAGATCTCTCCTGTTGGCAACTCGAAATCTCTACGA
GATAACAGTTTGTCTAGGAAACTTTCCTCCCAACTAAAGAGCGATGACTTAGGAAGTAAACGTGCCCTCA
TCACCGCCCTTACACACTGCTAGTCATTCATGTACATTGCGATTGTGCCTTGGTGCGGGGCGGTTCCTAG
GCACCATTTATCTTGTATTCCTGTACATCCCCTCCTTAATACTTTAATTGGAGCCACATCGTTTTGCCAT
GTTGATCTGTTTCCTTTCCCTGTAACAATGGTTACATTCTAAACGAACTAACTTGCTTTGAAGAAATCTA
CGAATTGATAGACTGTATATGCGCCCCTTTTCTTTATTAAAAACGCTTAACAAGGTAACAATATACGTAA
CATTCGAACAAGTACCAAGATAACTATATAACGGCTTATATAACTATC"""

def getRepeats(seq):
    seq = seq.replace("\n", "")
    repeated = {}

    for length in range(6, 11):
        subSequences = [seq[i:i+length] for i in range(len(seq) - length + 1)]
        counts = Counter(subSequences)
        repeated[length] = {sub: count for sub, count in counts.items() if count > 1}

    return repeated

repeats = getRepeats(S)

allRepeats = []
for length, subs in repeats.items():
    for sub, count in subs.items():
        allRepeats.append((sub, count))

allRepeatsSorted = sorted(allRepeats, key=lambda x: x[1], reverse=True)

labels, values = zip(*allRepeatsSorted)

plt.figure(figsize=(18, 7))
plt.bar(labels, values, color='skyblue', edgecolor='black')
plt.title("All Repeated Subsequences (6–10 bases) Sorted by Occurrences")
plt.xlabel("Subsequence")
plt.ylabel("Occurrences")
plt.xticks(rotation=90, fontsize=8)
plt.tight_layout()
plt.show()
